FROM python:3.10-slim as build
LABEL maintainer="adam.dobrawy{at}siecobywatelska.pl"

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN apt-get update \
 && apt-get install -y --no-install-recommends g++ git make nano \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt \
 && apt-get remove -y g++ && apt-get autoremove -y
ENV PYTHONUNBUFFERED=1
COPY . .
CMD [ "python", "./daemon.py" ]
